version: "3.9"

services:
  pg_100:
    container_name: pg_100
    image: postgres:12
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: test